model_list:
  - model_name: "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
    litellm_params:
      model: "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
      api_key: null  

litellm_settings:
  modify_params: true  # Boolean values in YAML should be in lowercase.
  set_verbose: true
  cache: false